#! /bin/bash
cd ./build
rm -rf *
cp ../load .
cmake .. -DPROJ=$1 -DTOOLCHAIN=/home/share/kun/k210/tool-chain/kendryte-toolchain/bin && make
python3 /home/share/kun/k210/isp/isp_auto.py -d /dev/ttyUSB[0-9] /home/share/kun/k210/stand_alone_sdk/kendryte-standalone-sdk-0.5.6/build/$1.bin -b 200000
python3 /home/share/kun/k210/isp/kflash.py -p /dev/ttyUSB[0-9] /home/share/kun/k210/stand_alone_sdk/kendryte-standalone-sdk-0.5.6/build/$1.bin
